-- Run this once in the new Supabase project's SQL Editor to create the table the app uses.
create table if not exists public.ds_students (
  id             bigint generated by default as identity primary key,
  student_name   text not null,
  student_number text not null unique,
  section_number text,
  password       text not null,
  progress       jsonb not null default '{}'::jsonb,
  created_at     timestamptz not null default now()
);

-- The app talks to the table directly with the anon key, so allow the anon role.
alter table public.ds_students enable row level security;

create policy "anon select" on public.ds_students for select to anon using (true);
create policy "anon insert" on public.ds_students for insert to anon with check (true);
create policy "anon update" on public.ds_students for update to anon using (true) with check (true);
create policy "anon delete" on public.ds_students for delete to anon using (true);
